# ----------------------------------------
# Project: Thronestead — FrontEnd Production Deploy Config
# Environment: Production (Netlify)
# Version: 6.14.2025.20.12
# ----------------------------------------

[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "18"                # Ensures compatibility for any Node-based tooling

[build.processing.html]
  pretty_urls = true                 # Allow /page to resolve /page.html

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
