# ----------------------------------------
# Project: Thronestead — FrontEnd Production Deploy Config
# Environment: Production (Netlify)
# Version: 6.14.2025.20.12
# ----------------------------------------

[build]
  publish = "."                       # Root directory for static files
  command = ""                        # No build command needed for pure HTML/CSS/JS

[context.production.environment]
  NODE_VERSION = "18"                # Ensures compatibility for any Node-based tooling

[build.processing.html]
  pretty_urls = true                 # Allow /page to resolve /page.html

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

