[build]
  publish = "dist" 
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
