-- Migration: create kingdom_villages table with local management fields

CREATE TABLE public.kingdom_villages (
  village_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  kingdom_id integer REFERENCES public.kingdoms(kingdom_id),
  village_name text,
  village_type text,
  created_at timestamp with time zone DEFAULT now(),
  is_capital boolean DEFAULT false,
  population integer DEFAULT 0,
  defense_level integer DEFAULT 0,
  prosperity integer DEFAULT 100,
  last_updated timestamp with time zone DEFAULT now()
);
