-- Migration: add training_catalog table

CREATE TABLE public.training_catalog (
  unit_id serial not null,
  unit_name text not null,
  tier integer null,
  training_time integer null,
  cost_wood integer null default 0,
  cost_stone integer null default 0,
  cost_iron_ore integer null default 0,
  cost_gold integer null default 0,
  cost_gems integer null default 0,
  cost_food integer null default 0,
  cost_coal integer null default 0,
  cost_livestock integer null default 0,
  cost_clay integer null default 0,
  cost_flax integer null default 0,
  cost_tools integer null default 0,
  cost_wood_planks integer null default 0,
  cost_refined_stone integer null default 0,
  cost_iron_ingots integer null default 0,
  cost_charcoal integer null default 0,
  cost_leather integer null default 0,
  cost_arrows integer null default 0,
  cost_swords integer null default 0,
  cost_axes integer null default 0,
  cost_shields integer null default 0,
  cost_armour integer null default 0,
  cost_wagon integer null default 0,
  cost_siege_weapons integer null default 0,
  cost_jewelry integer null default 0,
  cost_spear integer null default 0,
  cost_horses integer null default 0,
  cost_pitchforks integer null default 0,
  constraint training_catalog_pkey primary key (unit_id)
) TABLESPACE pg_default;
