-- Migration: add kingdom_castle_progression, kingdom_nobles, kingdom_knights
-- and extend kingdom_troop_slots with bonus slot columns

-- Add bonus columns to troop slots
ALTER TABLE public.kingdom_troop_slots
  ADD COLUMN castle_bonus_slots integer DEFAULT 0,
  ADD COLUMN noble_bonus_slots integer DEFAULT 0,
  ADD COLUMN knight_bonus_slots integer DEFAULT 0;

-- Castle progression table
CREATE TABLE public.kingdom_castle_progression (
  kingdom_id integer PRIMARY KEY REFERENCES public.kingdoms(kingdom_id),
  castle_level integer DEFAULT 1,
  xp integer DEFAULT 0,
  last_updated timestamp with time zone DEFAULT now()
);

-- Nobles table
CREATE TABLE public.kingdom_nobles (
  noble_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  kingdom_id integer REFERENCES public.kingdoms(kingdom_id),
  noble_name text,
  title text,
  level integer DEFAULT 1,
  experience integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now()
);

-- Knights table
CREATE TABLE public.kingdom_knights (
  knight_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  kingdom_id integer REFERENCES public.kingdoms(kingdom_id),
  knight_name text,
  level integer DEFAULT 1,
  experience integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now()
);
